### PR TITLE
Strapi 4.5.6 update

### PR DESCRIPTION
**Pull request by ChrisHinchey**
Signed-off-by: Christopher Andrew Hinchey <chinchey@mitre.org>

### CODE REVIEW

**Review by GavMason — CHANGES_REQUESTED** [review]
The version numbers are missing a dot.

**Review by GavMason — COMMENTED** [review]
I fixed the issue in this commit.

**Comment by GavMason** [comment]
After review with the fix everything looks good to me.

**Review by GavMason — APPROVED** [review]

**Comment by ChrisHinchey** [comment]
Thank you for catching that.  I thought it was resolved when I chose the versions in the CLI.

**Pull request merged**
